import { describe, it, expect } from 'vitest';
import { createTemplate, addSection, addBand, addElement, addStyle } from '@jsonpdf/template';
import { renderPdf } from '../src/renderer.js';
import { PluginRegistry, textPlugin, linePlugin, listPlugin } from '@jsonpdf/plugins';

describe('end-to-end: static template renders to valid PDF', () => {
  it('renders a template with text, line, and list elements', async () => {
    let template = createTemplate({ name: 'E2E Test' });

    template = addStyle(template, 'heading', {
      fontSize: 24,
      fontWeight: 'bold',
    });
    template = addStyle(template, 'body', {
      fontSize: 12,
    });

    template = addSection(template, {
      id: 'main',
      bands: [],
    });

    template = addBand(template, 'main', {
      id: 'content',
      type: 'body',
      height: 400,
      elements: [],
    });

    // Heading text
    template = addElement(template, 'content', {
      id: 'title',
      type: 'text',
      x: 0,
      y: 0,
      width: 532,
      height: 30,
      style: 'heading',
      properties: { content: 'Hello, JsonPDF!' },
    });

    // Horizontal divider
    template = addElement(template, 'content', {
      id: 'divider',
      type: 'line',
      x: 0,
      y: 35,
      width: 532,
      height: 1,
      properties: { color: '#cccccc', thickness: 1 },
    });

    // Body text with wrapping
    template = addElement(template, 'content', {
      id: 'body-text',
      type: 'text',
      x: 0,
      y: 45,
      width: 532,
      height: 60,
      style: 'body',
      properties: {
        content:
          'This is a static PDF generated by JsonPDF. It demonstrates text rendering with word wrapping across multiple lines within the available width.',
      },
    });

    // Dashed divider
    template = addElement(template, 'content', {
      id: 'dashed-line',
      type: 'line',
      x: 0,
      y: 115,
      width: 532,
      height: 1,
      properties: { color: '#999999', thickness: 1, dashPattern: [4, 2] },
    });

    // Bullet list
    template = addElement(template, 'content', {
      id: 'features',
      type: 'list',
      x: 0,
      y: 125,
      width: 532,
      height: 100,
      style: 'body',
      properties: {
        listType: 'bullet',
        items: [
          'Text with word wrapping and alignment',
          'Lines (solid and dashed)',
          'Bullet, numbered, and lettered lists',
        ],
      },
    });

    // Numbered list
    template = addElement(template, 'content', {
      id: 'steps',
      type: 'list',
      x: 0,
      y: 240,
      width: 532,
      height: 100,
      style: 'body',
      properties: {
        listType: 'numbered',
        items: ['Define template as JSON', 'Pass to renderer', 'Get PDF bytes'],
      },
    });

    // Rich text with styled runs
    template = addElement(template, 'content', {
      id: 'rich-text',
      type: 'text',
      x: 0,
      y: 350,
      width: 532,
      height: 30,
      style: 'body',
      properties: {
        content: [
          { text: 'This is ' },
          { text: 'bold text', styleOverrides: { fontWeight: 'bold' } },
          { text: ' mixed with normal text.' },
        ],
      },
    });

    const result = await renderPdf(template);

    // Verify valid PDF
    expect(result.bytes).toBeInstanceOf(Uint8Array);
    expect(result.bytes.length).toBeGreaterThan(0);
    expect(result.pageCount).toBe(1);

    // Verify PDF header
    const header = new TextDecoder().decode(result.bytes.slice(0, 5));
    expect(header).toBe('%PDF-');

    // Verify non-trivial size (should be at least a few KB with embedded fonts)
    expect(result.bytes.length).toBeGreaterThan(1000);
  });

  it('renders autoHeight band correctly', async () => {
    let template = createTemplate({ name: 'AutoHeight Test' });
    template = addSection(template, { id: 'main', bands: [] });
    template = addBand(template, 'main', {
      id: 'auto-band',
      type: 'body',
      height: 10,
      autoHeight: true,
      elements: [],
    });
    template = addElement(template, 'auto-band', {
      id: 'long-text',
      type: 'text',
      x: 0,
      y: 0,
      width: 200,
      height: 10,
      properties: {
        content:
          'This text is much longer than the declared band height and should cause the band to grow when autoHeight is enabled.',
      },
    });

    const result = await renderPdf(template);
    expect(result.pageCount).toBe(1);
    expect(result.bytes.length).toBeGreaterThan(0);
  });

  it('renders with custom PluginRegistry passed in options', async () => {
    // Create a custom registry
    const customRegistry = new PluginRegistry();
    customRegistry.register(textPlugin);
    customRegistry.register(linePlugin);
    customRegistry.register(listPlugin);

    let template = createTemplate({ name: 'Custom Registry Test' });
    template = addSection(template, { id: 'main', bands: [] });
    template = addBand(template, 'main', {
      id: 'content',
      type: 'body',
      height: 100,
      elements: [],
    });
    template = addElement(template, 'content', {
      id: 'text',
      type: 'text',
      x: 0,
      y: 0,
      width: 532,
      height: 30,
      properties: { content: 'Rendered with custom registry' },
    });

    const result = await renderPdf(template, { registry: customRegistry });
    expect(result.pageCount).toBe(1);
    expect(result.bytes.length).toBeGreaterThan(0);

    // Verify PDF header
    const header = new TextDecoder().decode(result.bytes.slice(0, 5));
    expect(header).toBe('%PDF-');
  });
});
