import type { Template } from '@jsonpdf/core';
import { DEFAULT_FONTS } from '@jsonpdf/template';

/**
 * Invoice demo template shown when the editor first loads.
 * Based on examples/invoice/template.json with default data values
 * embedded in the dataSchema so the Preview tab renders immediately.
 */
export const DEMO_TEMPLATE: Template = {
  version: '1.0',
  name: 'Invoice',
  description: 'A multi-page invoice with line items, page headers/footers, and data binding.',
  page: {
    width: 612,
    height: 792,
    margins: { top: 40, right: 40, bottom: 40, left: 40 },
  },
  dataSchema: {
    type: 'object',
    properties: {
      invoiceNumber: { type: 'string', default: 'INV-2025-0042' },
      date: { type: 'string', default: 'January 15, 2025' },
      dueDate: { type: 'string', default: 'February 14, 2025' },
      company: {
        type: 'object',
        properties: {
          name: { type: 'string', default: 'Acme Solutions Inc.' },
          address: {
            type: 'string',
            default: '100 Innovation Drive, Suite 500, San Francisco, CA 94105',
          },
          website: { type: 'string', default: 'https://acme-solutions.example.com' },
        },
      },
      customer: {
        type: 'object',
        properties: {
          name: { type: 'string', default: 'Global Retail Partners LLC' },
          address: {
            type: 'string',
            default: '2500 Commerce Way, Floor 12, New York, NY 10001',
          },
          email: { type: 'string', default: 'accounts@globalretail.example.com' },
        },
      },
      items: {
        type: 'array',
        default: [
          {
            description: 'Enterprise License — Annual Subscription',
            qty: 1,
            unitPrice: 12000.0,
            total: 12000.0,
          },
          {
            description: 'Premium Support Package (12 months)',
            qty: 1,
            unitPrice: 3600.0,
            total: 3600.0,
          },
          {
            description: 'Custom API Integration — Setup Fee',
            qty: 1,
            unitPrice: 5000.0,
            total: 5000.0,
          },
          {
            description: 'Data Migration Service — Per Table',
            qty: 8,
            unitPrice: 750.0,
            total: 6000.0,
          },
          {
            description: 'Training Session — On-Site (Full Day)',
            qty: 3,
            unitPrice: 2500.0,
            total: 7500.0,
          },
          {
            description: 'Cloud Storage — 500GB Tier (Monthly)',
            qty: 12,
            unitPrice: 49.99,
            total: 599.88,
          },
          {
            description: 'SSL Certificate — Wildcard (Annual)',
            qty: 2,
            unitPrice: 199.0,
            total: 398.0,
          },
          {
            description: 'CDN Bandwidth — 10TB Package',
            qty: 1,
            unitPrice: 850.0,
            total: 850.0,
          },
          {
            description: 'Database Optimization Consulting (Hours)',
            qty: 16,
            unitPrice: 275.0,
            total: 4400.0,
          },
          {
            description: 'Load Testing — Performance Audit',
            qty: 1,
            unitPrice: 3200.0,
            total: 3200.0,
          },
          {
            description: 'Security Audit — Penetration Testing',
            qty: 1,
            unitPrice: 4500.0,
            total: 4500.0,
          },
          {
            description: 'Monitoring Dashboard — Setup & Config',
            qty: 1,
            unitPrice: 1800.0,
            total: 1800.0,
          },
          {
            description: 'Alerting Rules — Custom Configuration',
            qty: 5,
            unitPrice: 350.0,
            total: 1750.0,
          },
          {
            description: 'Backup Solution — Daily Snapshots (Annual)',
            qty: 1,
            unitPrice: 2400.0,
            total: 2400.0,
          },
          {
            description: 'Disaster Recovery Plan — Documentation',
            qty: 1,
            unitPrice: 1500.0,
            total: 1500.0,
          },
          {
            description: 'User Provisioning Module — License',
            qty: 50,
            unitPrice: 15.0,
            total: 750.0,
          },
          {
            description: 'SSO Integration — SAML/OAuth Setup',
            qty: 1,
            unitPrice: 2200.0,
            total: 2200.0,
          },
          {
            description: 'Analytics Dashboard — Custom Reports',
            qty: 4,
            unitPrice: 600.0,
            total: 2400.0,
          },
          {
            description: 'Webhook Configuration — Per Endpoint',
            qty: 6,
            unitPrice: 125.0,
            total: 750.0,
          },
          {
            description: 'Email Template Customization',
            qty: 10,
            unitPrice: 85.0,
            total: 850.0,
          },
          {
            description: 'API Rate Limit Increase — Enterprise Tier',
            qty: 1,
            unitPrice: 500.0,
            total: 500.0,
          },
          {
            description: 'Compliance Report — SOC 2 Documentation',
            qty: 1,
            unitPrice: 3000.0,
            total: 3000.0,
          },
          {
            description: 'White-Label Branding Package',
            qty: 1,
            unitPrice: 4000.0,
            total: 4000.0,
          },
          {
            description: 'Multi-Region Deployment — Setup',
            qty: 2,
            unitPrice: 1750.0,
            total: 3500.0,
          },
          {
            description: 'Quarterly Business Review — Meeting',
            qty: 4,
            unitPrice: 0.0,
            total: 0.0,
          },
          {
            description: 'Dedicated IP Address — Annual',
            qty: 1,
            unitPrice: 1200.0,
            total: 1200.0,
          },
          {
            description: 'Custom Domain Configuration',
            qty: 3,
            unitPrice: 150.0,
            total: 450.0,
          },
          {
            description: 'Log Aggregation Service (Monthly)',
            qty: 12,
            unitPrice: 75.0,
            total: 900.0,
          },
          {
            description: 'Status Page — Hosted Solution (Annual)',
            qty: 1,
            unitPrice: 600.0,
            total: 600.0,
          },
          {
            description: 'GraphQL API Gateway — Setup',
            qty: 1,
            unitPrice: 2800.0,
            total: 2800.0,
          },
          { description: 'Mobile SDK License', qty: 2, unitPrice: 1500.0, total: 3000.0 },
          {
            description: 'PDF Report Generation Module',
            qty: 1,
            unitPrice: 950.0,
            total: 950.0,
          },
          {
            description: 'Onboarding Concierge — Per Session',
            qty: 6,
            unitPrice: 200.0,
            total: 1200.0,
          },
        ],
        items: {
          type: 'object',
          properties: {
            description: { type: 'string' },
            qty: { type: 'number' },
            unitPrice: { type: 'number' },
            total: { type: 'number' },
          },
        },
      },
      subtotal: { type: 'number', default: 81047.88 },
      taxRate: { type: 'number', default: 8.75 },
      taxAmount: { type: 'number', default: 7091.69 },
      grandTotal: { type: 'number', default: 88139.57 },
    },
  },
  defaultStyle: { fontFamily: 'Inter' },
  styles: {
    'company-name': {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#1a1a2e',
    },
    'invoice-label': {
      fontSize: 10,
      color: '#888888',
      textAlign: 'right',
    },
    'invoice-value': {
      fontSize: 10,
      fontWeight: 'bold',
      textAlign: 'right',
    },
    'section-label': {
      fontSize: 8,
      fontWeight: 'bold',
      color: '#888888',
    },
    'customer-text': {
      fontSize: 10,
      color: '#333333',
    },
    'col-header': {
      fontSize: 9,
      fontWeight: 'bold',
      color: '#ffffff',
      textDecoration: 'underline',
    },
    'col-header-right': {
      fontSize: 9,
      fontWeight: 'bold',
      color: '#ffffff',
      textAlign: 'right',
      textDecoration: 'underline',
    },
    'item-text': {
      fontSize: 9,
      color: '#333333',
    },
    'item-number': {
      fontSize: 9,
      color: '#333333',
      textAlign: 'right',
    },
    'summary-label': {
      fontSize: 10,
      textAlign: 'right',
      color: '#555555',
    },
    'summary-value': {
      fontSize: 10,
      textAlign: 'right',
    },
    'grand-total-label': {
      fontSize: 12,
      fontWeight: 'bold',
      textAlign: 'right',
      color: '#1a1a2e',
      borderBottom: { width: 2, color: '#1a1a2e' },
    },
    'grand-total-value': {
      fontSize: 12,
      fontWeight: 'bold',
      textAlign: 'right',
      color: '#1a1a2e',
      borderBottom: { width: 2, color: '#1a1a2e' },
    },
    footer: {
      fontSize: 8,
      color: '#999999',
      textAlign: 'center',
    },
    'thank-you': {
      fontSize: 9,
      fontStyle: 'italic',
      color: '#888888',
      textAlign: 'center',
    },
    link: {
      fontSize: 10,
      color: '#2563eb',
    },
  },
  fonts: [...DEFAULT_FONTS],
  sections: [
    {
      id: 'invoice',
      bands: [
        {
          id: 'page-header',
          type: 'pageHeader',
          height: 75,
          elements: [
            {
              id: 'company-name',
              type: 'text',
              x: 0,
              y: 5,
              width: 250,
              height: 25,
              style: 'company-name',
              properties: { content: '{{ company.name }}' },
            },
            {
              id: 'company-website',
              type: 'text',
              x: 0,
              y: 28,
              width: 250,
              height: 12,
              style: 'link',
              styleOverrides: { fontSize: 8 },
              properties: {
                content: [{ text: '{{ company.website }}', link: '{{ company.website }}' }],
              },
            },
            {
              id: 'company-address',
              type: 'text',
              x: 0,
              y: 42,
              width: 250,
              height: 14,
              style: 'customer-text',
              styleOverrides: { fontSize: 8, color: '#888888' },
              properties: { content: '{{ company.address }}' },
            },
            {
              id: 'invoice-label',
              type: 'text',
              x: 350,
              y: 5,
              width: 182,
              height: 14,
              style: 'invoice-label',
              properties: { content: 'INVOICE' },
            },
            {
              id: 'invoice-number',
              type: 'text',
              x: 350,
              y: 20,
              width: 182,
              height: 14,
              style: 'invoice-value',
              properties: { content: '#{{ invoiceNumber }}' },
            },
            {
              id: 'date-label',
              type: 'text',
              x: 350,
              y: 38,
              width: 90,
              height: 12,
              style: 'invoice-label',
              properties: { content: 'Date:' },
            },
            {
              id: 'date-value',
              type: 'text',
              x: 440,
              y: 38,
              width: 92,
              height: 12,
              style: 'invoice-value',
              properties: { content: '{{ date }}' },
            },
            {
              id: 'due-label',
              type: 'text',
              x: 350,
              y: 52,
              width: 90,
              height: 12,
              style: 'invoice-label',
              properties: { content: 'Due:' },
            },
            {
              id: 'due-value',
              type: 'text',
              x: 440,
              y: 52,
              width: 92,
              height: 12,
              style: 'invoice-value',
              properties: { content: '{{ dueDate }}' },
            },
            {
              id: 'header-line',
              type: 'line',
              x: 0,
              y: 70,
              width: 532,
              height: 1,
              properties: { color: '#1a1a2e', thickness: 2 },
            },
          ],
        },
        {
          id: 'bill-to',
          type: 'title',
          height: 65,
          elements: [
            {
              id: 'bill-to-label',
              type: 'text',
              x: 0,
              y: 5,
              width: 100,
              height: 12,
              style: 'section-label',
              properties: { content: 'BILL TO' },
            },
            {
              id: 'customer-name',
              type: 'text',
              x: 0,
              y: 20,
              width: 300,
              height: 14,
              style: 'customer-text',
              styleOverrides: { fontWeight: 'bold' },
              properties: { content: '{{ customer.name }}' },
            },
            {
              id: 'customer-address',
              type: 'text',
              x: 0,
              y: 36,
              width: 300,
              height: 12,
              style: 'customer-text',
              properties: { content: '{{ customer.address }}' },
            },
            {
              id: 'customer-email',
              type: 'text',
              x: 0,
              y: 50,
              width: 300,
              height: 12,
              style: 'link',
              properties: {
                content: [
                  {
                    text: '{{ customer.email }}',
                    link: 'mailto:{{ customer.email }}',
                  },
                ],
              },
            },
          ],
        },
        {
          id: 'col-header',
          type: 'columnHeader',
          height: 22,
          backgroundColor: '#1a1a2e',
          elements: [
            {
              id: 'ch-desc',
              type: 'text',
              x: 8,
              y: 4,
              width: 260,
              height: 14,
              style: 'col-header',
              properties: { content: 'Description' },
            },
            {
              id: 'ch-qty',
              type: 'text',
              x: 278,
              y: 4,
              width: 60,
              height: 14,
              style: 'col-header-right',
              properties: { content: 'Qty' },
            },
            {
              id: 'ch-price',
              type: 'text',
              x: 348,
              y: 4,
              width: 80,
              height: 14,
              style: 'col-header-right',
              properties: { content: 'Unit Price' },
            },
            {
              id: 'ch-total',
              type: 'text',
              x: 438,
              y: 4,
              width: 86,
              height: 14,
              style: 'col-header-right',
              properties: { content: 'Total' },
            },
          ],
        },
        {
          id: 'line-item',
          type: 'detail',
          height: 20,
          dataSource: 'items',
          elements: [
            {
              id: 'item-desc',
              type: 'text',
              x: 8,
              y: 3,
              width: 260,
              height: 14,
              style: 'item-text',
              properties: { content: '{{ item.description }}' },
            },
            {
              id: 'item-qty',
              type: 'text',
              x: 278,
              y: 3,
              width: 60,
              height: 14,
              style: 'item-number',
              properties: { content: '{{ item.qty }}' },
            },
            {
              id: 'item-price',
              type: 'text',
              x: 348,
              y: 3,
              width: 80,
              height: 14,
              style: 'item-number',
              properties: { content: '{{ item.unitPrice | money }}' },
            },
            {
              id: 'item-total',
              type: 'text',
              x: 438,
              y: 3,
              width: 86,
              height: 14,
              style: 'item-number',
              properties: { content: '{{ item.total | money }}' },
            },
            {
              id: 'item-line',
              type: 'line',
              x: 0,
              y: 19,
              width: 532,
              height: 1,
              properties: { color: '#eeeeee', thickness: 0.5 },
            },
          ],
        },
        {
          id: 'no-items',
          type: 'noData',
          height: 40,
          elements: [
            {
              id: 'no-items-text',
              type: 'text',
              x: 0,
              y: 10,
              width: 532,
              height: 20,
              style: 'footer',
              styleOverrides: { fontSize: 12, fontStyle: 'italic' },
              properties: { content: 'No line items' },
            },
          ],
        },
        {
          id: 'subtotals',
          type: 'summary',
          height: 85,
          elements: [
            {
              id: 'summary-line',
              type: 'line',
              x: 330,
              y: 5,
              width: 202,
              height: 1,
              properties: { color: '#1a1a2e', thickness: 1 },
            },
            {
              id: 'subtotal-label',
              type: 'text',
              x: 330,
              y: 12,
              width: 100,
              height: 14,
              style: 'summary-label',
              properties: { content: 'Subtotal:' },
            },
            {
              id: 'subtotal-value',
              type: 'text',
              x: 438,
              y: 12,
              width: 94,
              height: 14,
              style: 'summary-value',
              properties: { content: '{{ subtotal | money }}' },
            },
            {
              id: 'tax-label',
              type: 'text',
              x: 330,
              y: 30,
              width: 100,
              height: 14,
              style: 'summary-label',
              properties: { content: 'Tax ({{ taxRate }}%):' },
            },
            {
              id: 'tax-value',
              type: 'text',
              x: 438,
              y: 30,
              width: 94,
              height: 14,
              style: 'summary-value',
              properties: { content: '{{ taxAmount | money }}' },
            },
            {
              id: 'total-line',
              type: 'line',
              x: 330,
              y: 50,
              width: 202,
              height: 1,
              properties: { color: '#1a1a2e', thickness: 1.5 },
            },
            {
              id: 'total-label',
              type: 'text',
              x: 330,
              y: 57,
              width: 100,
              height: 18,
              style: 'grand-total-label',
              properties: { content: 'Total:' },
            },
            {
              id: 'total-value',
              type: 'text',
              x: 438,
              y: 57,
              width: 94,
              height: 18,
              style: 'grand-total-value',
              properties: { content: '{{ grandTotal | money }}' },
            },
          ],
        },
        {
          id: 'page-footer',
          type: 'pageFooter',
          height: 20,
          elements: [
            {
              id: 'page-num',
              type: 'text',
              x: 0,
              y: 5,
              width: 532,
              height: 12,
              style: 'footer',
              properties: { content: 'Page {{ _pageNumber }} of {{ _totalPages }}' },
            },
          ],
        },
        {
          id: 'last-footer',
          type: 'lastPageFooter',
          height: 40,
          elements: [
            {
              id: 'thank-you',
              type: 'text',
              x: 0,
              y: 5,
              width: 532,
              height: 14,
              style: 'thank-you',
              properties: { content: 'Thank you for your business!' },
            },
            {
              id: 'last-page-num',
              type: 'text',
              x: 0,
              y: 22,
              width: 532,
              height: 12,
              style: 'footer',
              properties: { content: 'Page {{ _pageNumber }} of {{ _totalPages }}' },
            },
          ],
        },
      ],
    },
  ],
};
